# Generated by Django 5.1.7 on 2025-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='code_barre',
        ),
        migrations.AddField(
            model_name='produit',
            name='code_barre_image',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
