# Generated by Django 5.1.7 on 2025-10-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('VENTES', 'Rapport de ventes'), ('ACHATS', 'Rapport d’achats'), ('PERTE', 'Rapport de pertes'), ('STOCK', 'Rapport de stock global')], max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
