# Generated by Django 5.1.7 on 2025-10-15 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mouvementstock', '0002_initial'),
        ('produit', '0001_initial'),
        ('rapport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='genere_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='mouvements',
            field=models.ManyToManyField(blank=True, to='mouvementstock.mouvementstock'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='produits',
            field=models.ManyToManyField(blank=True, to='produit.produit'),
        ),
    ]
